### ISSUE TITLE
更新拼音输入法后出现错误 IndexError: pop from empty list 

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1047]
```
What version of the product are you using? On what operating system?
OS (Linux distributions, UNIX or ...):
ubuntu 10.04
IBus version:
1.3.7
Input method name and version:
ibus-pinyin 1.3.10

从软件源 ppa.launchpad.net/shawn-p-huang/ppa/ubuntu 更新后，运行ibus-setup出现错误输出：
Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 462, in <module>
    setup = Setup()
  File "/usr/share/ibus/setup/main.py", line 80, in __init__
    self.__init_ui()
  File "/usr/share/ibus/setup/main.py", line 197, in __init_ui
    self.__engines = self.__bus.list_engines()
  File "/usr/lib/pymodules/python2.6/ibus/bus.py", line 133, in list_engines
    return map(serializable.deserialize_object, engines)
  File "/usr/lib/pymodules/python2.6/ibus/serializable.py", line 54, in deserialize_object
    o.deserialize (struct)
  File "/usr/lib/pymodules/python2.6/ibus/enginedesc.py", line 112, in deserialize
    self.__rank = struct.pop(0)
IndexError: pop from empty list

删除ibus-pinyin软件包后，ibus-setup可以打开设置窗口，同时发现输入法列表为空，添加输入法按钮不可用，但此时已经安装sunpinyin输入法。
尝试彻底删除ibus以及相关软件包后，再删除 .cache/ibus 和 /usr 目录下所有ibus旧文件，重新安装ibus，问题依旧（添加输入法按钮不可用）。再安装ibus-pinyin，错误输出和先前相同。
```

Original issue reported on code.google.com by `Sukest` on 2010-08-08 08:48:48

**Comment by fujiwarat** [comment]
I think this is not reproduced in the latest ibus.
