### ISSUE TITLE
[ibus-table-others] translit build with warning

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1049]
```
/usr/bin/ibus-table-createdb  -n translit.db -s translit.txt
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/tabdict.py", line 62, in __init__
    self._key_id = tab_dict[xm_key]
KeyError: u'\xf6'
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/tabdict.py", line 62, in __init__
    self._key_id = tab_dict[xm_key]
KeyError: u'\xe4'
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/tabdict.py", line 62, in __init__
    self._key_id = tab_dict[xm_key]
KeyError: u'\xfc'
ö is not in tab_dict
ä is not in tab_dict
ü is not in tab_dict

```

Original issue reported on code.google.com by `lidaobing` on 2010-08-09 14:21:48

**Comment by mike-fabian** [comment]
Original google code issue was: https://code.google.com/p/ibus/issues/detail?id=1030

**Comment by mike-fabian** [comment]
I fixed this long ago in ibus-table. 
No such warnings appear now, translit can be used
with any keyboard layout, and öäü work as intended.
