### ISSUE TITLE
evolution core dump with ibus 1.4.0

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1358]
```
OS: Arch Linux

Software Version:
ibus 1.4.0-1
ibus-pinyin 1.3.99.20110706-1
evolution 3.2.1-1
evolution-data-server 3.2.1-1
evolution-exchange 3.2.1-1
evolution-webcal 2.32.0-1
python-evolution 2.32.0-8

Core Dump Stack BackTracker:

(gdb) bt
#0  0x00007f0353597204 in ?? () from /usr/lib/libgtk-3.so.0
#1  0x00007f03535968f2 in gtk_im_context_get_preedit_string () from /usr/lib/libgtk-3.so.0
#2  0x00007f0325f38b09 in ?? () from /usr/lib/gtk-2.0/2.10.0/immodules/im-ibus.so
#3  0x00007f035353ac39 in ?? () from /usr/lib/libgtk-3.so.0
#4  0x00007f035192335f in ?? () from /usr/lib/libgdk-3.so.0
#5  0x00007f0352a177fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#6  0x00007f0352a17ff8 in ?? () from /usr/lib/libglib-2.0.so.0
#7  0x00007f0352a18532 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#8  0x00007f03535ae80d in gtk_main () from /usr/lib/libgtk-3.so.0
#9  0x00007f0352edc0e4 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#10 0x00007f0352eee06a in ?? () from /usr/lib/libgobject-2.0.so.0
#11 0x00007f0352ef76f1 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#12 0x00007f0352ef7892 in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#13 0x0000000000401f69 in ?? ()
#14 0x00007f035269413d in __libc_start_main () from /lib/libc.so.6


Any one have the same issue with me ? or can give me some advice ?


```

Original issue reported on code.google.com by `luoyi.ly` on 2011-10-24 03:01:37

**Comment by fujiwarat** [comment]
I cannot reproduce this issue in the latest ibus.
