### ISSUE TITLE
ibus-engine-mozc crash ibus 1.5.18, ibus 1.5.17 don't crash

### ISSUE THREAD

**Issue by ncaq** [ibus/ibus#2007]
Which distribution and version?:
Gentoo

Which desktop environment and version?:
xmonad
I xmonad setting in [ncaq/.xmonad](https://github.com/ncaq/.xmonad).

Which session type?:
X11

Which application and version?:
mozc: 2.23.2815.102

IBus version?:
IBus 1.5.18

Issue description:
ibus-engine-mozc dumped core when ibus 1.5.18

Steps to reproduce:
1. ibus-daemon --xim --replace

Can you reproduce your problem when you restart ibus-daemon? (yes / no):
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
2018-05-09T10:59:25 ncaq@karen/pts/0(130) ~
% ibus-daemon --xim --replace --verbose

(ibus-ui-gtk3:7710): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:7710): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(ibus-ui-gtk3:7710): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):
I did not check.

# version

when ibus 1.5.17, don't crash.

# core dump

~~~
2018-05-09T10:57:18 ncaq@karen/pts/3(0) ~
% coredumpctl gdb 6753
           PID: 6753 (ibus-engine-moz)
           UID: 1000 (ncaq)
           GID: 1000 (ncaq)
        Signal: 11 (SEGV)
     Timestamp: Wed 2018-05-09 10:18:31 JST (38min ago)
  Command Line: /usr/libexec/ibus-engine-mozc --ibus
    Executable: /usr/libexec/ibus-engine-mozc
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (ncaq)
       Boot ID: fa9cb107bfd549ab96f8615542996a57
    Machine ID: d8e54a7d7b1a07bfd7a9413f581d4472
      Hostname: karen
       Storage: /var/lib/systemd/coredump/core.ibus-engine-moz.1000.fa9cb107bfd549ab96f8615542996a57.6753.1525828711000000.lz4
       Message: Process 6753 (ibus-engine-moz) of user 1000 dumped core.

GNU gdb (Gentoo 8.1 p1) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/libexec/ibus-engine-mozc...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 6753]
[New LWP 6769]
[New LWP 6772]
[New LWP 6924]
[New LWP 6925]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/libexec/ibus-engine-mozc --ibus'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f976d79e0a0 in ?? () from /usr/lib64/libibus-1.0.so.5
[Current thread is 1 (Thread 0x7f976dbbc7c0 (LWP 6753))]
(gdb) bt
#0  0x00007f976d79e0a0 in ?? () from /usr/lib64/libibus-1.0.so.5
#1  0xe15ea8912e9df700 in ?? ()
#2  0x00007f975c012890 in ?? ()
#3  0x00007f975c012880 in ?? ()
#4  0x00007f976d7b1e60 in ?? () from /usr/lib64/libibus-1.0.so.5
#5  0x00007f975c013860 in ?? ()
#6  0x00007f976d49ce6c in ?? () from /usr/lib64/libgio-2.0.so.0
#7  0x00007f976cec37f5 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#8  0x00007f976cec3bb8 in ?? () from /usr/lib64/libglib-2.0.so.0
#9  0x00007f976cec3ed2 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#10 0x00007f976d7b349c in ?? () from /usr/lib64/libibus-1.0.so.5
#11 0x0000000000000000 in ?? ()
~~~

**Comment by ncaq** [comment]
fixed.
thank you.
