### ISSUE TITLE
Cannot find engine table:quick-classic

### ISSUE THREAD

**Issue by psaavedra** [ibus/ibus#2052]
* Which distribution and version?: 
I'm building from scratch for Yocto (Sumo)

* Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
I'm working on recipes for IBus in Yocto so I'm building IBus components cross compiling from the scratch.. Now I have an almost functional set of recipes for ibus, ibus-table and ibus-table-chinese and ibus-pinyin. 

* Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

* Which application and version?: 
matchbox-terminal 0.1

* IBus version?: 
1.5.18

* Issue description:
  My problem is IBus throws a `Cannot find engine table:quick-classic` when I set the IM with ibus-setup or ibus engine `table:quick-classic`  but I can see the `table:quick-classic` engine in the `ibus`:

```
ibus list-engine | grep class
table:quick-classic - QuickClassic
```

  This is the hierarchy of the processes:
  ```
root      4239  0.0  0.0  16000  1124 ?        Ss   17:43   0:00 xinit /etc/X11/Xsession -- /usr/bin/Xorg :0 -br -pn
root      4242  0.6  0.2 229084 18908 tty2     S<sl+ 17:43   0:00  \_ /usr/bin/Xorg :0 -br -pn
root      4245  0.0  0.0  44416  2520 ?        S    17:43   0:00  \_ su -c /etc/matchbox/nodm-session uitx
root      4251  0.0  0.0 268568  5428 ?        Sl   17:43   0:00      \_ /usr/libexec/at-spi-bus-launcher --launch-immediately
root      4268  0.0  0.0  28692  2856 ?        S    17:43   0:00      |   \_ /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
uitx      4269  0.7  0.3 677440 28964 ?        Ssl  17:43   0:00      \_ matchbox-terminal
uitx      4279  0.0  0.0  55768  5476 ?        S    17:43   0:00          \_ matchbox-window-manager -use_titlebar no -use_cursor no
uitx      4301  0.0  0.0  18224  2776 pts/0    Ss+  17:43   0:00          \_ /bin/sh
root      4259  0.0  0.0  37996   328 ?        S    17:43   0:00 dbus-launch --autolaunch=8eb60eb948764453a7b483c079581fb4 --binary-syntax --close-stderr
uitx      4260  0.0  0.0  38276  5548 ?        Ss   17:43   0:00 /lib/systemd/systemd --user
uitx      4261  0.0  0.0 212316  2048 ?        S    17:43   0:00  \_ (sd-pam)
root      4262  0.0  0.0  28692   260 ?        Ss   17:43   0:00 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 5 --print-address 7 --session
uitx      4275  0.0  0.0  37996   328 ?        S    17:43   0:00 dbus-launch --sh-syntax --exit-with-session
uitx      4276  0.0  0.0  28692  2152 ?        Ss   17:43   0:00 /usr/bin/dbus-daemon --syslog --fork --print-pid 5 --print-address 7 --session
uitx      4278  0.0  0.0 346084  6232 ?        Ssl  17:43   0:00 /usr/bin/ibus-daemon -x -d -r
uitx      4282  0.0  0.0 265476  4788 ?        Sl   17:43   0:00  \_ /usr/libexec/ibus-dconf
uitx      4283  0.6  0.2 379256 23060 ?        Sl   17:43   0:00  \_ /usr/libexec/ibus-ui-gtk3
uitx      4308  1.0  0.2 334440 22988 ?        Sl   17:43   0:00  \_ python3 /usr/share/ibus-table/engine/main.py --ibus
uitx      4286  0.1  0.1 297352 14212 ?        Sl   17:43   0:00 /usr/libexec/ibus-x11 --kill-daemon
uitx      4290  0.0  0.0 263424  4800 ?        Sl   17:43   0:00 /usr/libexec/ibus-portal
  ```
  Any idea about what is going wrong in my setup?

* Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes

* Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

```
** (ibus-ui-gtk3:3340): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(ibus-ui-gtk3:3340): IBUS-WARNING **: panel.vala:255: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:3340): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:3340): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.IBus.SetGlobalEngine: GDBus.Error:org.freedesktop.DBus.Error.Failed: Set global engine failed: The connection is closed

(ibus-ui-gtk3:3340): IBUS-WARNING **: panel.vala:837: Switch engine to table:quick-classic failed.
```

* Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
> ** (ibus-ui-gtk3:3340): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

I googled that warning and hit https://bbs.archlinux.org/viewtopic.php?id=176663
NO_AT_BRIDGE might be useful for you but I'm not sure if it's relative with this issue.

> (ibus-ui-gtk3:3340): IBUS-WARNING **: panel.vala:837: Switch engine to table:quick-classic failed.

I'd suggest to check debug.log
1. `mv $HOME/.cache/ibus-table/debug.log $HOME/.cache/ibus-table/debug.log.bak`
1. `ibus restart`
1. Press Super-space and re-enable your ibus engine.
1. Check the content of debug.log

**Comment by psaavedra** [comment]
That is what the debug.log says:

```
Compatible database /home/uitx/.local/share/ibus-table/tables/quick-classic-user.db found.
Connect to the database /home/uitx/.local/share/ibus-table/tables/quick-classic-user.db.
create_indexes()
TabEngine.__init__() self._engine_name = quick-classic
self._page_down_keys=[16777215, 65366, 46, 61]
self._commit_keys=[32]
failed to create engine quick-classic
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/factory.py", line 84, in do_create_engine
    self.dbdict[engine_name])
  File "/usr/share/ibus-table/engine/table.py", line 1545, in __init__
    self.db)
  File "/usr/share/ibus-table/engine/table.py", line 358, in __init__
    orientation=self._orientation)
  File "/usr/share/ibus-table/engine/table.py", line 410, in get_new_lookup_table
    round=True)
TypeError: gobject `IBusLookupTable' doesn't support property `cursor_pos'
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/factory.py", line 84, in do_create_engine
    self.dbdict[engine_name])
  File "/usr/share/ibus-table/engine/table.py", line 1545, in __init__
    self.db)
  File "/usr/share/ibus-table/engine/table.py", line 358, in __init__
    orientation=self._orientation)
  File "/usr/share/ibus-table/engine/table.py", line 410, in get_new_lookup_table
    round=True)
TypeError: gobject `IBusLookupTable' doesn't support property `cursor_pos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/factory.py", line 92, in do_create_engine
    raise Exception("Cannot create engine %s" %engine_name)
Exception: Cannot create engine quick-classic
```

**Comment by psaavedra** [comment]
It seems something doesn't fits well with the GObject introspection. This is what I have in a good environment:

```
 |  Method resolution order:
 |      LookupTable
 |      gi.repository.IBus.LookupTable
 |      gi.repository.IBus.Serializable
 |      gi.repository.IBus.Object
 |      gi.repository.GObject.InitiallyUnowned
 |      gi.overrides.GObject.Object
 |      gi.repository.GObject.Object
 |      gi._gi.GObject
 |      __builtin__.object
```

And this what I have in the Yocto env:

```
 |  Method resolution order:
 |      LookupTable
 |      Serializable
 |      Object
 |      gi.repository.GObject.InitiallyUnowned
 |      gi.overrides.GObject.Object
 |      gi.repository.GObject.Object
 |      gi._gi.GObject
 |      __builtin__.object
```

**Comment by fujiwarat** [comment]
>   File "/usr/share/ibus-table/engine/table.py", line 410, in get_new_lookup_table
>     round=True)
> TypeError: gobject `IBusLookupTable' doesn't support property `cursor_pos'

Is that really python 3?

Can you check the process of ibus-table?

> % ps -ef | grep ibus-table
> uitx      4308  1.0  0.2 334440 22988 ?        Sl   17:43   0:00  \_ python3 /usr/share/ibus-table/engine/main.py --ibus

Can you check IBus.LookuoTable directly with python3?

```
% cat a.py
from gi import require_version as gi_require_version
gi_require_version('IBus', '1.0')
from gi.repository import IBus
IBus.init()
table = IBus.LookupTable(
    page_size=10,
    cursor_pos=0,
    cursor_visible=True,
    round=True)

% python3 a.py
```

**Comment by psaavedra** [comment]
Pretty sure:

```
Python 3.5.5 (default, Oct 23 2018, 08:47:14)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi import require_version as gi_require_version
>>> gi_require_version('IBus', '1.0')
>>> from gi.repository import IBus
>>> IBus.init()
>>> table = IBus.LookupTable(
...     page_size=10,
...     cursor_pos=0,
...     cursor_visible=True,
...     round=True)
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
TypeError: gobject `IBusLookupTable' doesn't support property `cursor_pos'

```

**Comment by psaavedra** [comment]
The error thrown and shown above is is becouse IBus.py in the `gi/overrides` for the Python3 environment:

```
cp /usr/lib/python2.7/dist-packages/gi/overrides/IBus.py /usr/lib/python3.5/site-packages/gi/overrides/
```

```
$ python3
Python 3.5.5 (default, Oct 23 2018, 08:47:14)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi import require_version as gi_require_version
>>> gi_require_version('IBus', '1.0')
>>> from gi.repository import IBus
>>> IBus.init()
>>> table = IBus.LookupTable(
...     page_size=10,
...     cursor_pos=0,
...     cursor_visible=True,
...     round=True)
>>>
```

**Comment by psaavedra** [comment]
Fixed.

**Comment by fujiwarat** [comment]
IBus tarball installs IBus.py in the correct python2 and python3.

**Comment by psaavedra** [comment]
The problem is about how Yocto build the environment to build the package. I don't think it is a problem of the IBus configuration actually. In the `configure.ac` file:

```
../ibus-1.5.18/configure.ac:    pyoverridesdir=`$PYTHON -c "import gi; print(gi._overridesdir)"`
```

; the `pyoverridesdir` generated by the Yocto's configure step returns: `/home/igalia/psaavedra/yocto/builds/test/tmp/work/core2-64-poky-linux/ibus/1.5.18-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/gi/overrides/`

This directory is not in under the `/home/igalia/psaavedra/yocto/builds/test/tmp/work/core2-64-poky-linux/ibus/1.5.18-r0/image` so it is not shipped into the distributable package built by `bitbake` (in Yocto).

That is the reason why this file is missing in my image.  I will work in how to fix this in the Yocto recipe.

JFYI,  this work is part of a downstream project based to build a custom Linux distro in Yocto but I have the idea of submit all this work to meta-oe once it was mature enough. Nowadays Yocto lacks of support of IBus and only it has support for UIM.

**Comment by fujiwarat** [comment]
OK, thank you for your evaluation.
