### ISSUE TITLE
ibus-ui-gtk3 crash reports

### ISSUE THREAD

**Issue by gunnarhj** [ibus/ibus#2203]
Hi @fujiwarat,

We have received a bunch of ibus-ui-gtk3 crash reports in Ubuntu. They are from various ibus versions, and not identical, so this is a somewhat unconventional issue. These are the reports:

- https://launchpad.net/bugs/1829297

- https://launchpad.net/bugs/1843195

- https://launchpad.net/bugs/1843958

- https://launchpad.net/bugs/1869484

- https://launchpad.net/bugs/1870747

I thought that you may want to spend a few minutes on reviewing them. Possibly there is some more common denominator but ibus-ui-gtk3...

I'll be happy to provide further information if I can.

**Comment by fujiwarat** [comment]
> https://launchpad.net/bugs/1829297

I'd say it would be a fontconfig issue.

> https://launchpad.net/bugs/1843195
>  Backtrace stopped: previous frame inner to this frame (corrupt stack?)
StacktraceSource:

Seems to fail to get StacktraceSource. I guess a debug package have a problem and I cannot evaluate the problem without more information.

> https://launchpad.net/bugs/1843958
> https://launchpad.net/bugs/1870843

I guess an old value was saved in the gsettings, which causes your problem and a new user account would not reproduce the problem.

> https://launchpad.net/bugs/1869484
> https://launchpad.net/bugs/1870747
> #4  0x0000564e7d16c236 in panel_construct ()
> #5  0x0000564e7d150d94 in _application_bus_name_acquired_cb_gd_bus_signal_callback ()

I don't know the API of _application_bus_name_acquired_cb_gd_bus_signal_callback() and I guess it would be an API relative with Unity and panel_construct() receives the wrong DBus.

**Comment by gunnarhj** [comment]
Thanks a lot for taking the time to review it, @fujiwarat. I suppose Ubuntu's desktop team will need to take a closer look after Ubuntu 20.04 has been released (right now they are loaded with other work), and then your hints will be valuable.
