### ISSUE TITLE
ibus-table-chinese 1.8.3: source tree is not rady to off-source-tree build type

### ISSUE THREAD

**Issue by kloczek** [ibus/ibus#2309]
I'm not sure whgre to report ibus-table-chinese however I see suggestion to repot per ibus components issues here.

Problem is that when ibus-table-chinese is build with `cmake -B <build_dir> <cmake_options>; cmake /usr/bin/cmake --build <build_dir>` it fails because `CONVERT_DB` macro defined in tables/CMakeLists.txt assumes that `targetName` file passed to that macro will be in local directory.
Here is build log showing that bug:
```
+ /usr/bin/cmake -B noarch-redhat-linux-gnu -D BUILD_SHARED_LIBS=ON -D CMAKE_AR=/usr/bin/gcc-ar -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_C_FLAGS_RELEASE=-DNDEBUG -D CMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D CMAKE_Fortran_FLAGS_RELEASE=-DNDEBUG -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_NM=/usr/bin/gcc-nm -D CMAKE_RANLIB=/usr/bin/gcc-ranlib -D CMAKE_VERBOSE_MAKEFILE=ON -D DBUILD_SHARED_LIBS=ON -D INCLUDE_INSTALL_DIR=/usr/include -D LIB_INSTALL_DIR=/usr/lib64 -D LIB_SUFFIX=64 -D SHARE_INSTALL_PREFIX=/usr/share -D SYSCONF_INSTALL_DIR=/etc -S .
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


[array] db files=array30.db;array30-big.db
[cangjie] db files=cangjie3.db;cangjie5.db;cangjie-big.db
[cantonese] db files=cantonese.db;cantonhk.db;cantonyale.db;jyutping.db
[easy] db files=easy-big.db
[erbi] db files=erbi.db;erbi-qs.db
[quick] db files=quick3.db;quick5.db;quick-classic.db
[scj] db files=scj6.db
[stroke5] db files=stroke5.db
[wu] db files=wu.db
[wubi-haifeng] db files=wubi-haifeng86.db
[wubi-jidian] db files=wubi-jidian86.db
[yong] db files=yong.db
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_SHARED_LIBS
    CMAKE_AR
    CMAKE_CXX_FLAGS_RELEASE
    CMAKE_C_FLAGS_RELEASE
    CMAKE_Fortran_FLAGS_RELEASE
    CMAKE_NM
    CMAKE_RANLIB
    DBUILD_SHARED_LIBS
    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    LIB_SUFFIX
    SHARE_INSTALL_PREFIX
    SYSCONF_INSTALL_DIR


-- Build files have been written to: /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu
+ /usr/bin/cmake --build noarch-redhat-linux-gnu -j48 --verbose -j1
/usr/bin/cmake -S/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3 -B/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu/CMakeFiles /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu//CMakeFiles/progress.marks
/usr/bin/gmake  -f CMakeFiles/Makefile2 all
gmake[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu'
/usr/bin/gmake  -f tables/yong/CMakeFiles/convert_yong.dir/build.make tables/yong/CMakeFiles/convert_yong.dir/depend
gmake[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu'
cd /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3 /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/tables/yong /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu/tables/yong /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu/tables/yong/CMakeFiles/convert_yong.dir/DependInfo.cmake --color=
Dependee "/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu/tables/yong/CMakeFiles/convert_yong.dir/DependInfo.cmake" is newer than depender "/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu/tables/yong/CMakeFiles/convert_yong.dir/depend.internal".
Dependee "/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu/tables/yong/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu/tables/yong/CMakeFiles/convert_yong.dir/depend.internal".
Scanning dependencies of target convert_yong
gmake[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu'
/usr/bin/gmake  -f tables/yong/CMakeFiles/convert_yong.dir/build.make tables/yong/CMakeFiles/convert_yong.dir/build
gmake[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu'
[  2%] Building yong table
cd /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/noarch-redhat-linux-gnu/tables/yong && /usr/bin/ibus-table-createdb -n yong.db -s /home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/yong.txt
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/tabcreatedb.py", line 503, in <module>
    main()
  File "/usr/share/ibus-table/engine/tabcreatedb.py", line 394, in main
    source = open(_OPTIONS.source, mode='r', encoding='UTF-8').read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/ibus-table-chinese-1.8.3/yong.txt'
gmake[2]: *** [tables/yong/CMakeFiles/convert_yong.dir/build.make:83: tables/yong/yong.db] Error 1
gmake[2]: *** Deleting file 'tables/yong/yong.db'
```

**Comment by fujiwarat** [comment]
You could find ibus-table-chinese here
https://github.com/ibus/ibus/wiki/BugReport

**Comment by mike-fabian** [comment]
> I'm not sure whgre to report ibus-table-chinese however I see suggestion to repot per ibus components issues here.

Upstream for ibus-table-chinese is here:

https://github.com/mike-fabian/ibus-table-chinese


https://github.com/mike-fabian/ibus-table-chinese/issues

I think the build issue is fixed already, or do you still have a problem building it?

**Comment by kloczek** [comment]
OK thank you.
