### ISSUE TITLE
ibus-1.5.25.tar.gz fail to build due to the missing denylist.txt

### ISSUE THREAD

**Issue by zhmars** [ibus/ibus#2335]
Issue description:

Hi, I got following error when building the latest release `1.5.25`.  The file `denylist.txt` could be found in repo, but not exist in tarball.

```
 $ ./autogen.sh --prefix='/usr' --sysconfdir='/etc' --libdir='/usr/lib' --enable-gtk-doc
 $ make

...
./gensimple.py \
    --input=/usr/share/X11/xkb/rules/evdev.xml \
    --output=simple.xml.in \
    --version=1.5.25.`date '+%Y%m%d'` \
    --exec-path=@libexecdir\@/ibus-engine-simple \
    --iso-path=/usr/share/xml/iso-codes/iso_639.xml \
    --first-language \

Traceback (most recent call last):
  File "/tmp/pkg/ibus/ibus-1.5.25/engine/./gensimple.py", line 385, in <module>
    denylist = parse_denylist('%s/%s' % ( mydir, 'denylist.txt'))
  File "/tmp/pkg/ibus/ibus-1.5.25/engine/./gensimple.py", line 330, in parse_denylist
    f = codecs.open(denyfile, 'r', encoding='utf-8')
  File "/usr/lib/python3.9/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: './denylist.txt'
make[2]: *** [Makefile:966: simple.xml.in] Error 1
make[2]: Leaving directory '/tmp/pkg/ibus/ibus-1.5.25/engine'
make[1]: *** [Makefile:689: all-recursive] Error 1
make[1]: Leaving directory '/tmp/pkg/ibus/ibus-1.5.25'
make: *** [Makefile:596: all] Error 2

```

**Comment by fujiwarat** [comment]
You could export "SAVE_DIST_FILES=1" before you run autogen.sh.
