### ISSUE TITLE
Unable to start ibus in the XFCE4 environment

### ISSUE THREAD

**Issue by andruska** [ibus/ibus#2462]
Trying to use `ibus` with `ibus-typing-booster` plugin. Ibus daemon wont start. When running `ibus-setup` it doesnt see already running `ibus-daemon` (started by `systemd` on user login) and offers to assign already existing environment variables and start `ibus-daemon` again. And this second time it partly works without functional `ibus-typing-booster` plugin. I am using freshly installed `archlinux`. Weird mess.

Similar to [#2383](https://github.com/ibus/ibus/issues/2383#issue-1136416146)

```
yay -S ibus-daemon
```

```
$ systemctl --user status ibus@user
● ibus@user.service - Intelligent Input Bus
     Loaded: loaded (/usr/lib/systemd/user/ibus@.service; enabled; preset: enabled)
     Active: active (running) since Tue 2022-11-29 02:19:11 EET; 31min ago
       Docs: man:ibus-daemon(1)
   Main PID: 800 (ibus-daemon)
      Tasks: 7 (limit: 9364)
     Memory: 8.2M
        CPU: 154ms
     CGroup: /user.slice/user-60139.slice/user@60139.service/app.slice/app-ibus.slice/ibus@user.service
             ├─800 /usr/bin/ibus-daemon --replace --xim
             └─823 /usr/lib/ibus/ibus-dconf

nov   29 02:19:11 systemd[793]: Started Intelligent Input Bus.
nov   29 02:19:11 ibus-daemon[800]: portal is not running: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.IBus exited with status 1
```
```
$ ibus-daemon -rx --verbose

(ibus-ui-gtk3:2809): IBUS-WARNING **: 02:32:35.531: panel.vala:310: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.
Traceback (most recent call last):
  File "/usr/share/ibus-typing-booster/engine/main.py", line 129, in <module>
    import factory
  File "/usr/share/ibus-typing-booster/engine/factory.py", line 34, in <module>
    import hunspell_table
  File "/usr/share/ibus-typing-booster/engine/hunspell_table.py", line 55, in <module>
    import itb_emoji
  File "/usr/share/ibus-typing-booster/engine/itb_emoji.py", line 44, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

(ibus-ui-gtk3:2809): IBUS-WARNING **: 02:33:09.406: ibus_bus_call_sync: org.freedesktop.IBus.SetGlobalEngine: GDBus.Error:org.freedesktop.DBus.Error.Failed: Set global engine failed: Timeout was reached

(ibus-ui-gtk3:2809): IBUS-WARNING **: 02:33:09.406: panel.vala:913: Switch engine to typing-booster failed.
```
```
# uname -a
Linux 6.0.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:24 +0000 x86_64 GNU/Linux

```
```
# pacman -Qi xfwm4
Name            : xfwm4
Version         : 4.16.1-3
```
```
# echo $XDG_SESSION_TYPE
x11
```
```
# pacman -Qi ibus
Name            : ibus
Version         : 1.5.27-1
```

**Comment by mike-fabian** [comment]
`ModuleNotFoundError: No module named 'packaging'` means that python3-packaging is not installed.

On Arch: https://archlinux.org/packages/extra/any/python-packaging/

**Comment by fujiwarat** [comment]
This should not be report to ibus but ibus-typing-booster.
