### ISSUE TITLE
Ibus prevents typing in blender

### ISSUE THREAD

**Issue by psads-git** [ibus/ibus#2697]
- Fedora 41

- XFCE

- X11

- [blender](https://www.blender.org/)

- IBus 1.5.31-rc1

_Issue description:_

Cannot type in blender.

_Steps to reproduce:_

1. Open blender.
2. Hit F3. 
3. A search menu pops up.
4. Try to type something. 

_Can you reproduce your problem when you restart ibus-daemon? (yes / no):_ 

After running `ibus exit`, no issue occurs while using blender. However, after running `ibus-daemon --xim &`, the reported issue returns.

_Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)_

I do not see any errors.

_Can you reproduce your problem with a new user account instead of the current your account? (yes / no):_ 

I am the single user of the machine.

**Comment by mike-fabian** [comment]
It looks like `ibus_engine_commit_text()` is ignored by blender.

If using direct input mode, for example ibus-anthy with 英数 (_A) mode where ASCII letter are just passed through by returning False from the key processing, the characters appear in the F3 search box in blender. Everything which needs commits like Fullwidth Latin mode or typing Japanese text fails. When trying to type Japanese, I see the preedit (not on-the-spot), I can do henkan (convert to kanji) but the commit seems to fail. See this video:

https://github.com/user-attachments/assets/3072a5b4-1bd7-4540-b567-59d2a17af938

Probably a bug in blender. See also:
https://projects.blender.org/blender/blender/issues/129757

**Comment by psads-git** [comment]
Thanks, Mike, for your answer!

I am actually the reporter of the issue against blender you mention. In particular, I call you attention to the comment:

https://projects.blender.org/blender/blender/issues/129757#issuecomment-1335065

Now, changing subject and using the opportunity that I am here in touch with you, I got the following, and I am not sure you aware of:

https://issues.chromium.org/issues/40146869#comment17

**Comment by psads-git** [comment]
Hi Mike,

Thanks a lot for your input and for taking the time to share it. Much appreciated!

Best regards.

**Comment by fujiwarat** [comment]
Deleted unrelative comments while I always said you should waiit for my evaluation at first.

> Try to type something.

Which IBus engine did you try?

If you set "English (US)" XKB engine, I think Blender works fine with your typing.

If you need a commit-text feature of the XIM, "COMPOUND_TEXT" encoding is required in libX11.
I debugged libX11.so with Blender and found `setlocale` is not initialized before `XOpenIM()` is called and Blender uses C enconding which does not support the commit-text feature.

Blender calls `setlocale()` two times with "C" locale:

#0  setlocale (category=6, locale=0x7fffaab16858 "C")
#1  0x000055555652ba79 in BLT_lang_init() ()
#2  0x0000555556477b21 in WM_init(bContext*, int, char const**) ()
#3  0x0000555555873e18 in main ()

#0  setlocale (category=0, locale=0x7fff90999a90 "C")
#1  0x00007fffeb8187dd in _Py_PreInitializeFromPyArgv ()
    at /lib64/libpython3.13.so.1.0
#2  0x00007fffeb6dc557 in Py_PreInitialize () at /lib64/libpython3.13.so.1.0
#3  0x0000555556d2fbd6 in BPY_python_start(bContext*, int, char const**) ()
#4  0x0000555556479943 in WM_init(bContext*, int, char const**) ()
#5  0x0000555555873e18 in main ()

#0  XOpenIM
    (display=0x7fff90cdc100, rdb=0x7fffffffd630, res_name=0x55555935170d "", res_class=0x7fffffffd810 "\t") at xlibi18n/IMWrap.c:116
#1  0x000055555674387a in GHOST_SystemX11::processEvents(bool) ()
#2  0x0000555556403f1d in WM_main(bContext*) ()
#3  0x0000555555875080 in main ()

Blender needs to call `setlocale(LC_ALL, "")` beffore it calls `XOpenIM()`.
